### ISSUE TITLE
Interpreting negative DFBETA

### ISSUE THREAD

**Issue by mturchin20** [rujinwang/EPIC#11]
Hello,

I was wondering what the interpretation of a negative DFBETA is in the context of EPIC/cell-type enrichment? Perhaps in both a statistical sense and a biological sense? 

Thanks,
Michael

**Comment by yuchaojiang** [comment]
Hi, I would not read too much into the plus-minus signs of the DFBETA statistics. Both are significantly influential genes that drive the significant beta regression coefficient in the cell type of interest. The DFBETA is for testing genes' influence, while the overarching goal is to test a cell type's enrichment of the GWAS loci.
