### ISSUE TITLE
Intuition behind sign of DFBETA

### ISSUE THREAD

**Issue by ndejay** [rujinwang/EPIC#13]
Hello,

I have a hopefully quick question concerning how to interpret the sign of DFBETA.

EPIC considers a cell type to be influential if gene expression specificity is significantly positively linear w.r.t gene-disease GWAS associations.  In other words, if highly specifically expressed genes demonstrate stronger GWAS associations, then it is a relevant cell type.

Then, EPIC considers a gene to be influential within a cell type if significantly influences this linear relationship.  While I understand how a gene driving a positive relationship (DFBETA>0) would be influential, I would love to hear your thoughts on how to best interpret a gene driving a negative relationship (DFBETA<0).  Should these be ignored?

Thanks!

Nic

**Comment by yuchaojiang** [comment]
Hi, please see our response here https://github.com/rujinwang/EPIC/issues/11
