### ISSUE TITLE
EPIC cholesky decomposition warning

### ISSUE THREAD

**Issue by mturchin20** [rujinwang/EPIC#14]
Hello, I have a question about a warning I've been seeing when running EPIC.

When running EPIC, I often get the following warning from a cholesky decomposition step:
1: In chol.default(R, pivot = TRUE) :
  the matrix is either rank-deficient or indefinite
2: In chol.default(R, pivot = TRUE) :
  the matrix is either rank-deficient or indefinite

I'm pretty sure this is coming from the following line in the get_gene_chisq() function during the gene-gene correlation correction steps:
R.star.chol <- cholesky_decomposition(R.star)

It seems like periodically an index gene will have some other gene in the area that, when trying to adjust for, this warning is thrown. It maybe happens once or at most twice per index gene with another surrounding gene. The method runs to completion though regardless of the warning, and I don't find NAs anywhere. 

I'm able to grab the index gene and the other gene that's being corrected for when this warning gets thrown. It looks something like this:
> combineObject$warningList
                                          message                                             call      
 [1,] "ENSG00000093009" "ENSG00000184113" "the matrix is either rank-deficient or indefinite" expression
 [2,] "ENSG00000188280" "ENSG00000161133" "the matrix is either rank-deficient or indefinite" expression
 [3,] "ENSG00000161180" "ENSG00000128228" "the matrix is either rank-deficient or indefinite" expression
 [4,] "ENSG00000253239" "ENSG00000211637" "the matrix is either rank-deficient or indefinite" expression
 [5,] "ENSG00000211643" "ENSG00000211644" "the matrix is either rank-deficient or indefinite" expression
 [6,] "ENSG00000211644" "ENSG00000211645" "the matrix is either rank-deficient or indefinite" expression

The first column is the index gene and the second column is the other gene. This is just a few example lines, but as I mentioned, if it happens, it's usually just once per index gene.

Is this something to be concerned about? Is this a reflection of sparseness somewhere in the data? If additional information would be useful I can try and provide it.

**Comment by yuchaojiang** [comment]
hi @rujinwang  can you please take a look and address this issue?

**Comment by mturchin20** [comment]
Hi @rujinwang @yuchaojiang, just wanted to follow up on this. Do either of you have any thoughts on whether this is a concerning warning or not? Or what might be the cause? 

Thanks!
Michael

**Comment by rujinwang** [comment]
Hi @mturchin20 , 
Thanks for your interest and follow-up with EPIC. I'm so sorry for the delay. I've been having communication gaps with Github over a couple of months. Just saw it. 

The warning arises when matrix is not full rank, which could be due to the limited sample size of LD reference panel but greater size (# of SNPs) of the gene pairs. We set part of the lower triangular matrix to be 0 matrix, making Cholesky decomposition still valid for gene-gene correlation calculation. It's not a big concern in real case. You can try to use UKB as LD reference, which could be helpful to resolve the warnings. But I don't think it would make a big difference to your downstream analyses results. 

Thanks. 

Best,
Rujin

**Comment by mturchin20** [comment]
Hi @rujinwang,

Great, that makes sense, thanks for the response and insight. I'll take a look at using UKB as an LD reference, but glad to know it's not something that should be a major concern.

Best,
Micahel

**Comment by mturchin20** [comment]
Hi @rujinwang,

Great, that makes sense, thanks for the response and insight. I'll take a look at using UKB as an LD reference, but glad to know it's not something that should be a major concern.

Best,
Michael
