### ISSUE TITLE
Processing GTEx data

### ISSUE THREAD

**Issue by weifangliu** [rujinwang/EPIC#2]
Hi, could you provide scripts for how you processed GTEx data or provide the processed data for 22 chromosomes? Thank you!

**Comment by yuchaojiang** [comment]
The GTEx data (v8) is downloaded from the GTEx portal. We performed log2 transformation on the tissue-specific TPM measurements with an added pseudo-count. Note that we focused on genes that are highly specific in at least
one tissue. See Note A in S1 Text for more details.

**Comment by weifangl-cw** [comment]
Thank you for the clarification. I have a follow-up question: in the manuscript it states "For tissue-specific bulk RNA-seq data from GTEx, we first calculate a tissue specificity score for each gene [12],..., and then perform log2 transformation on the tissue-specific TPM measurements with an added pseudo-count."

I went to the [documentation page of [12]](http://lulushang.org/docs/Projects/CoCoNet/Reproduce) (there is a section named CALCULATE GENE SPECIFICITY BY CELL TYPE) and it seems they performed log transformation before calculating tissue specificity scores. 

My question is what is the reason of doing this in one way versus another? Thank you!

**Comment by weifangliu** [comment]
Thank you for the clarification. I have a follow-up question: in the manuscript it states "For tissue-specific bulk RNA-seq data from GTEx, we first calculate a tissue specificity score for each gene [12],..., and then perform log2 transformation on the tissue-specific TPM measurements with an added pseudo-count."

I went to the [documentation page of [12]](http://lulushang.org/docs/Projects/CoCoNet/Reproduce) (there is a section named CALCULATE GENE SPECIFICITY BY CELL TYPE) and it seems they performed log transformation before calculating tissue specificity scores.

My question is what is the reason of doing this in one way versus another? Thank you!

**Comment by rujinwang** [comment]
In Shang et al. (CoCoNet), they performed double quantile normalization first on the log10(rpkm+1) and calculated gene specificity scores to select a list of genes with high specificity. 
EPIC didn't not perform any extra normalization steps on the cell-type specific TPM. I don't know why CoCoNet adopted the double quantile normalization step. 

As we mentioned, the only reason we computed gene specificity score is to subset genes of high cell type specificity. I don't think it really matters if we performed log transformation before or after.

**Comment by weifangliu** [comment]
Thanks for your reply. Performing log transformation before or after wouldn't change the ranking, but if I do log transformation before computing gene specificity scores, I only get ~3k genes with specificity scores >=5. I guess my question would be does the number of genes included in the analysis matter? Also, how did you deal with genes with IQR=0?

**Comment by rujinwang** [comment]
It's an open question. We want to get ~8k genes (close to the number of genes used in CoCoNet).
