### ISSUE TITLE
The bug when runing with scRNA data in your vignettes

### ISSUE THREAD

**Issue by Al-Esther** [rujinwang/EPIC#3]
Hi, I found your package could not run when using the scRNA-seq you provided in you vignettes. Could you pls fix these bugs?

First of all, colnames of scRNA.loc and gtex.loc are not the same, add names(scRNA.loc)=c("V1","V2","V3","V4","V5") could make it continue.
Secondly, the gene id of scRNAseq (symbol name)is not consistent with gene tests' id(ensemble id).
Thirdly, I converted the ID to be consistent by myself then the bugs came in function: prioritize_relevance().
Error in Matrix::bdiag(chol.inv.list[seq_len(length(chrs))]) %*% as.matrix(gene_expr.keep) : 
  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 88
What I found up to now is that there is issues in gene name match among gene expression data, gene tests and gene loc.

Could you please let me know if I did anythong wrong or could you pls further check your pipeline and function when using scRNAseq data?

Many thanks!

**Comment by Al-Esther** [comment]
Or could you please provide your ID convert lists?
I don't know which way would be faster.
Thanks.

**Comment by rujinwang** [comment]
Hi @Al-Esther, 
Thanks for your interest in EPIC. I've fixed the bug in processing the scRNA-seq data and unified gene names using the Ensembl gene ID. The current pipeline for scRNAseq works well on my end. 
We appreciate the feedback you provided and your patience. Please let me know if you have any questions. Thanks. 

Best, 
Rujin

**Comment by simonewebb** [comment]
I had the same issue as Al-Esther with the colnames of scRNA.loc. 

I've re-installed the new version of the package and am running the **'Prioritizing trait-relevant tissue(s) and cell type(s)'** step of the vignette on the tutorial scRNA-seq tutorial data. I think the updates to gene-names above have made this smoother - I can run the total tutorial now!

A few final minor points to add when running on scRNA-seq::

- When assigning influential_test.Demo.liver in the penultimate code block, I had to set `ct = "Ductal_cells"` rather than `ct = "Liver"`, since the test scRNA-seq data used does not have a 'Liver' cell type category
- #`dir.create(results_dir, showWarnings = FALSE)`   # added this line so that the directory would not error due to not existing for the following line:
#`save(prunein_qc_snp_to_gene.chr, file=file.path(results_dir, paste0(trait, "_prunein_", MAF, "_chr", chr, "_QC.rda")))`
- #prunein_qc_snp_to_gene <- prunein_qc_snp_to_gene.Demo    # added this line up ahead, because otherwise I would have an error that object 'prunein_qc_snp_to_gene' not found

Thanks for the great package!

Simone

**Comment by Al-Esther** [comment]
Thanks for your response, Rujin! It worked now. Just one more question about the results using your sample scRNAseq.
Is it showing no cell type passing the significance threshold?
Maybe this question is stupid: I used the cell type with the highest -log10p:
> influential_test.Demo.liver <- influential_testing(gene_pval = combine_POET_gene_pval.Demo,
                                                    gene_corr.mat = combine_gene_corr.mat.Demo, 
                                                    gene_expr = scRNA.rpkm, gene.loc = scRNA.loc, 
                                                    chrs = chr, ct = "Peri-islet_Schwann_cells")
Error in Matrix::bdiag(chol.inv.list[seq_len(length(chrs))]) %*% as.matrix(gene_expr.keep) : 
  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 88

Is this consistent with your analysis?
If not, would you mind adding the results in your vignettes?

Thanks for your great work!
Esther ^^

**Comment by rujinwang** [comment]
> influential_test.Demo.liver <- influential_testing(gene_pval = combine_POET_gene_pval.Demo,
> gene_corr.mat = combine_gene_corr.mat.Demo,
> gene_expr = scRNA.rpkm, gene.loc = scRNA.loc,
> chrs = chr, ct = "Peri-islet_Schwann_cells")

Great suggestions @simonewebb ! I've updated the vignette accordingly. Much appreciated!

Rujin

**Comment by rujinwang** [comment]
> I had the same issue as Al-Esther with the colnames of scRNA.loc.
> 
> I've re-installed the new version of the package and am running the **'Prioritizing trait-relevant tissue(s) and cell type(s)'** step of the vignette on the tutorial scRNA-seq tutorial data. I think the updates to gene-names above have made this smoother - I can run the total tutorial now!
> 
> A few final minor points to add when running on scRNA-seq::
> 
> * When assigning influential_test.Demo.liver in the penultimate code block, I had to set `ct = "Ductal_cells"` rather than `ct = "Liver"`, since the test scRNA-seq data used does not have a 'Liver' cell type category
> * #`dir.create(results_dir, showWarnings = FALSE)`   # added this line so that the directory would not error due to not existing for the following line:
>   #`save(prunein_qc_snp_to_gene.chr, file=file.path(results_dir, paste0(trait, "_prunein_", MAF, "_chr", chr, "_QC.rda")))`
> * #prunein_qc_snp_to_gene <- prunein_qc_snp_to_gene.Demo    # added this line up ahead, because otherwise I would have an error that object 'prunein_qc_snp_to_gene' not found
> 
> Thanks for the great package!
> 
> Simone

Great suggestions @simonewebb ! I've updated the vignette accordingly. Much appreciated!

Rujin

**Comment by rujinwang** [comment]
> Thanks for your response, Rujin! It worked now. Just one more question about the results using your sample scRNAseq. Is it showing no cell type passing the significance threshold? Maybe this question is stupid: I used the cell type with the highest -log10p:
> 
> > influential_test.Demo.liver <- influential_testing(gene_pval = combine_POET_gene_pval.Demo,
> > gene_corr.mat = combine_gene_corr.mat.Demo,
> > gene_expr = scRNA.rpkm, gene.loc = scRNA.loc,
> > chrs = chr, ct = "Peri-islet_Schwann_cells")
> > Error in Matrix::bdiag(chol.inv.list[seq_len(length(chrs))]) %*% as.matrix(gene_expr.keep) :
> > Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 88
> 
> Is this consistent with your analysis? If not, would you mind adding the results in your vignettes?
> 
> Thanks for your great work! Esther ^^

Hi @Al-Esther , 
In the vignette, we demonstrated EPIC to prioritize the most relevant tissue for low-density lipoprotein (LDL). It's no wonder that there are no significant relevant pancreatic islet cell types with LDL. This is consistent with our analysis. 
In our paper, we show significant enrichment results for Type 2 diabetes using the same scRNA-seq data. Thanks. 

Best, 
Rujin

**Comment by Al-Esther** [comment]
My bad. Should read more carefully.
Thanks for the quick responses!
Best,
Esther
