### ISSUE TITLE
LD pruning for common variants

### ISSUE THREAD

**Issue by simonewebb** [rujinwang/EPIC#5]
The below relates to the code directly at the beginning of the **'2.3 LD pruning for common variants'** section in the tutorial (http://htmlpreview.github.io/?https://github.com/rujinwang/EPIC/blob/master/vignettes/EPIC_vignette.html)

A note that I had to add the following lines into the tutorial (adapted from your source code), in order to begin the common variant pruning step:

```
anno_dictionary <- annotate_gene(upstream = 10, downstream = 1.5)

write.table(anno_dictionary, quote = FALSE, sep = "\t", row.names = FALSE,
               col.names = FALSE, file=file.path(out_dir, paste0("annotation_dictionary.txt")))

head(anno_dictionary)
```

I was otherwise getting errors that the file `out_dir/annotation_dictionary.txt` didn't exist, but I could see that the code I needed was commented out in your source code, so I grabbed it from there.

If there's something I missed, please let me know!

Testing package is otherwise going smoothly, well done on your great work for this

Thanks

Simone

**Comment by simonewebb** [comment]
Can I also please ask how long the plink pruning common variants step takes for the LDL example in tutorial?

In your documentation, you mention:

>  'Note that PLINK LD-pruning procedure would generate thousands of intermediate files for further data importing.'

I have quite a few files now (~220MB, ~50/60,000 files, 15hrs) and wondered whether this is likely to finish soon or if I should leave it for the weekend. 

My best guess is that there are 3 files per 31,060 genes in anno_dictionay, so we want 93,180 files? 

Thanks!

**Comment by rujinwang** [comment]
> The below relates to the code directly at the beginning of the **'2.3 LD pruning for common variants'** section in the tutorial (http://htmlpreview.github.io/?https://github.com/rujinwang/EPIC/blob/master/vignettes/EPIC_vignette.html)
> 
> A note that I had to add the following lines into the tutorial (adapted from your source code), in order to begin the common variant pruning step:
> 
> ```
> anno_dictionary <- annotate_gene(upstream = 10, downstream = 1.5)
> 
> write.table(anno_dictionary, quote = FALSE, sep = "\t", row.names = FALSE,
>                col.names = FALSE, file=file.path(out_dir, paste0("annotation_dictionary.txt")))
> 
> head(anno_dictionary)
> ```
> 
> I was otherwise getting errors that the file `out_dir/annotation_dictionary.txt` didn't exist, but I could see that the code I needed was commented out in your source code, so I grabbed it from there.
> 
> If there's something I missed, please let me know!
> 
> Testing package is otherwise going smoothly, well done on your great work for this
> 
> Thanks
> 
> Simone

Hi @simonewebb , 
Thanks for your interest in EPIC. Apologies for the confusion. Yes you are right. You can generate the file using `annotate_gene`. Actually we pre-stored the file in our package: https://github.com/rujinwang/EPIC/blob/master/package/inst/extdata/annotation_dictionary.txt. I update section 2.3 in the vignette for better clarification. We appreciate your feedback to improve the usage of EPIC!

Best, 
Rujin

**Comment by rujinwang** [comment]
> Can I also please ask how long the plink pruning common variants step takes for the LDL example in tutorial?
> 
> In your documentation, you mention:
> 
> > 'Note that PLINK LD-pruning procedure would generate thousands of intermediate files for further data importing.'
> 
> I have quite a few files now (~220MB, ~50/60,000 files, 15hrs) and wondered whether this is likely to finish soon or if I should leave it for the weekend.
> 
> My best guess is that there are 3 files per 31,060 genes in anno_dictionay, so we want 93,180 files?
> 
> Thanks!



> Can I also please ask how long the plink pruning common variants step takes for the LDL example in tutorial?
> 
> In your documentation, you mention:
> 
> > 'Note that PLINK LD-pruning procedure would generate thousands of intermediate files for further data importing.'
> 
> I have quite a few files now (~220MB, ~50/60,000 files, 15hrs) and wondered whether this is likely to finish soon or if I should leave it for the weekend.
> 
> My best guess is that there are 3 files per 31,060 genes in anno_dictionay, so we want 93,180 files?
> 
> Thanks!

Sorry for the late reply. Yes it may take days and you are expecting to get ~90k intermediate files in this step. 

Rujin

**Comment by simonewebb** [comment]
Morning Rujin,

Thanks so much for clarifying how to use the annotation_dictionary.txt here and in the tutorial - much appreciated! Happy that the feedback could be useful :)

I have just under 90k files now, hopefully everything has run un-interrupted - I'll have a go at section 2.4 onwards now.

All the best

Simone
