### ISSUE TITLE
NaN in chisq and pvalues

### ISSUE THREAD

**Issue by HJ234** [rujinwang/EPIC#6]
Hi! Thank you for the great program. 
I'm using EPIC on a single cell dataset of mine, and ran into an error in the prioritize_relevance step.
I get the following error when I run the command.
```
> enrichment <- prioritize_relevance(gene_pval = combine_POET_gene_pval, gene_corr.mat = combine_gene_corr.mat, gene_expr = scRNA.rpkm.new, gene.loc = scRNA.loc.new, verbose=TRUE) 
Prioritizing trait-relevant tissue(s) or cell type(s) for B
Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok,  : 
  0 (non-NA) cases
```

I've tried to read the script and find the source of error. It seems like the following command is producing NaN in chisq and pvalues for more than half of the genes in prunein_POET_gene_pval and combine_POET_gene_pval. This is causing the linear model (lm0 = lm(y.qc ~ x1.qc + x2.qc, weights = df.qc/2)) in prioritize_relevance to fail because of the NAs in y.qc.

```
pruneinObject <- get_gene_chisq(gene_pval = prunein_gene_pval, gene.loc = scRNA.loc, type = "POET", inter_dir = inter_dir)
combineObject <- get_gene_chisq(gene_pval = combine_gene_pval, gene.loc = scRNA.loc,type = "iPOET", inter_dir = inter_dir)
```

![Screenshot 2022-08-30 at 14 35 24](https://user-images.githubusercontent.com/109527205/187451716-df1376c8-03bb-4e5b-9365-95ed3e6e2617.png)

prunein_gene_pval, combine_gene_pval, scRNA.loc does not contain any NAs and the files within the intermediate directory doesn't look like it contains abnormal values. Would there be a reason for get_gene_chisq to produce this many NaN values and is there a way to fix this?

**Comment by rujinwang** [comment]
Hi @HJ234, 
Thanks for your interest in EPIC. It seems like the input `zhat` for `rs114176189` is `NAN`. EPIC calculated chisq statistics based on LD and zhat. Could you please check your input `zhat` and figure out why it's missing here? Thanks. 

Best, 
Rujin

**Comment by HJ234** [comment]
Hi, Thanks for spotting that. 
I found out that some of the beta and se values in the GWAS summary statistics were 0. 
I removed them prior to formatting the stats, which seems to work. Thank you!
