### ISSUE TITLE
Error in second_pruning(prunein_qc_snp_to_gene.Demo, plink_path, bfile_path,  :    object 'prunein_qc_snp_to_gene' not found

### ISSUE THREAD

**Issue by HJ234** [rujinwang/EPIC#7]
Hi, I was running the demo and ran into an error with second_pruning. 
```
> prunein_qc_snp_to_gene.chr <- second_pruning(prunein_snp_to_gene.Demo, plink_path, bfile_path, chr, prunein_dir)
Error in second_pruning(prunein_qc_snp_to_gene.Demo, plink_path, bfile_path,  : 
  object 'prunein_qc_snp_to_gene' not found
```

I changed the second_pruning function, so that it input 'prunein_qc_snp_to_gene' instead of object 'prunein_snp_to_gene' like the following. 

`second_pruning <- function(prunein_snp_to_gene, plink_path, bfile_path, chr, prunein_dir) {...}`
into 
`second_pruning <- function(prunein_qc_snp_to_gene, plink_path, bfile_path, chr, prunein_dir) {...}`

It started to work, but unfortunately, I ran into another error. 
```
> prunein_qc_snp_to_gene.chr <- second_pruning(prunein_snp_to_gene.Demo, plink_path, bfile_path, chr, prunein_dir)
Second-round LD pruning on 238: ENSG00000171094
LD pruning at  0.7 
 Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'maf_thres' not found 
```

Assigning maf_thres<-0.01 manually before running second_pruning resolved the issue.   

Would you possibly know why this is the case and is it possible to update the source code? Thank you.

**Comment by rujinwang** [comment]
Hi @HJ234 , 
Thank you so much for bringing up this issue. I've fixed the errors. Please re-install the package and feel free to let me know if you have any further questions. We appreciate your feedbacks. 

Best, 
Rujin

**Comment by HJ234** [comment]
Thanks for the quick reply and fixing the issue! I'll close the issue now.
