### ISSUE TITLE
Error in get_gene_chisq

### ISSUE THREAD

**Issue by Karimeltohamy** [rujinwang/EPIC#8]
Hi, I was running the demo and constantly get an error in chunk 20 (joint analysis for common and rare variants). The error states that the subscript is out of bounds, where could the problem be? I followed all the instructions and have not changed any of the scripts. See code below.
combineObject.Demo <- get_gene_chisq(gene_pval = combine_gene_pval.Demo, 
                                     gene.loc = gtex.loc, type = "POET", inter_dir = inter_dir)
combine_POET_gene_pval.Demo <- combineObject.Demo$gene_POET_pval
combine_gene_corr.mat.Demo <- combineObject.Demo$gene_corr.mat

Error msg: 
1: ENSG00000184731 chr = 2
Error in corr.POET[snps, snps, drop = FALSE] : subscript out of bounds

Please get back to me and thanks in advance!
Karim

**Comment by rujinwang** [comment]
Hi @Karim-tohamy , 
In `get_gene_chisq()`, please use `type = "iPOET"`. `POET` is for common variants and `iPOET` is for the combined. Thanks.
